### ISSUE TITLE
Play with Music Caster - context menu item for folders

### ISSUE THREAD

**Issue by cpo-ux** [elibroftw/music-caster#10]
Please provide the option in settings to disable the context menu entry.  That would me a lot nicer than searching through the registry and manually deleting the entries.  Thanks!

**Comment by elibroftw** [comment]
Would this be for just folders? Or do you want to remove the context menu for music files as well?

**Comment by cpo-ux** [comment]
I'd like to have the option to disable the context menu items for folders
and files (both together in one setting is okay for me).

**Comment by elibroftw** [comment]
Well, I just realized the menu does not pop up for files unless you've explicitly stated that you want to use MC to handle the file, so I'll only let users remove the folder context menu.
