### ISSUE TITLE
Feature Request: Dedicated "Play" Hotkey

### ISSUE THREAD

**Issue by VashSky** [elibroftw/music-caster#17]
I'm having a persistent issue where my playlist will randomly stop playing after around 2-4 hours of consistent playback. I'm not sure what is causing it but I will note that my playlist is around 25 hours long with tracks as long as 2 hours. I'd like to write a sort of "keep alive" script in which my device would occasionally hit a "play" hotkey as a workaround to keep this from happening in the future.

P.S. This build is awesome by the way, keep up the great work!

**Comment by elibroftw** [comment]
I might add a setting to never ignore media keys, but sometimes my key handler doesn't work, so try using the REST API.
https://github.com/elibroftw/music-caster/wiki/REST-API.

**Comment by VashSky** [comment]
Interestingly, the updates that have been released following this inquiry have actually resolved many of the issues I was experiencing. I can now get it to play continuously anywhere from 4-8 to even 10 hours, which is fantastic. I'll consider this issue resolved but I'm wondering if there is a link to all of the prior versions?

**Comment by elibroftw** [comment]
Prior versions? Why would you want prior versions? I delete prior versions for the same minor version.
