### ISSUE TITLE
Always shuffles when adding files or playlists

### ISSUE THREAD

**Issue by JoshuaPaulBarnard** [elibroftw/music-caster#21]
Hello, great app and thank you so much for making it!
I just installed it today and have been trying it out, but immediately came to a small snag.
Whenever I add files from a folder, or from a playlist to my current queue it will shuffle them.
This is frustrating as I like to listen to audiobooks and entire albums in sequence.

I can of course just reorganize the files in the current queue, but it is unfortunate that I cannot then save them and then recall them in that order.

Thank you very much!

**Comment by elibroftw** [comment]
![image](https://user-images.githubusercontent.com/21298211/106960350-f2c07d80-6709-11eb-98ca-cd1960e0bb96.png)
