### ISSUE TITLE
Multiple playback devices / Playback syncing of local and remote

### ISSUE THREAD

**Issue by chapmanjacobd** [elibroftw/music-caster#28]
I think you could have music syncing of local speakers and chromecast if you add a delay slider in the UI to delay the computer playback from 0ms to 20000ms (or maybe just a textbox input) then the user can choose how much delay they want to add to local speaker playback

**Comment by elibroftw** [comment]
I'll try to implement this tomorrow but if it's too difficult 🤷‍♂️

**Comment by elibroftw** [comment]
Check out the latest version. It might be kind of broke because I actually don't know how many bytes = a second for the WAV encoding I am using so I just guess 1024 * 1000 😂

**Comment by chapmanjacobd** [comment]
hmmmm I think it is working but how do I play multiple outputs at the same time? 

Can we make an option in settings called `Enable multiple devices` to change the Taskbar Tray Context Menu --> Select Device to be multi-select? 

Thanks!

**Comment by elibroftw** [comment]
> hmmmm I think it is working but how do I play multiple outputs at the same time? 
> 
> Can we make an option in settings called `Enable multiple devices` to change the Taskbar Tray `Context Menu` --> `Select Device` to be multi-select? 
> 
> Thanks!

Create a group in the home app, hit refresh devices and the group name should show up. Then cast to that group. I don't want to implement what you want because it would require significant testing. And I'm trying to work on some other project right now.

**Comment by chapmanjacobd** [comment]
I already have chromecast groups but Google won't let me add my PC's speakers to that group... sorry I didn't make that more clear. maybe I'll try opening up two instances of Music Caster and playing both that way

**Comment by elibroftw** [comment]
Yeah it's not even possible to stream live system audio to local speakers.

**Comment by chapmanjacobd** [comment]
that's why I was thinking of delaying the local speakers to match the chromecast but it only makes sense it local and chromecast is playing at the same time

**Comment by elibroftw** [comment]
Way too out of scope and comicated in my opinion. Better for your mixing software to support Chromecasts directly. Then they can create an endpoint for the Chromecast to listen to, keep track of the delay, play on local speakers with that delay, and then let you know the delay.

**Comment by chapmanjacobd** [comment]
okay I respect that. thanks for the time you spent implementing this feature. It is less annoying for the audio to be out of sync in the other room by 30s than for it to be slightly out of sync :)
