### ISSUE TITLE
Windows Defender detects PUA:WIn32/Pearfoos.A!ml

### ISSUE THREAD

**Issue by flyonthenet** [elibroftw/music-caster#29]
Hi all,

Windows Defender in Windows 10 detects this "Potentially Unwanted Software" in Music Caster.

![image](https://user-images.githubusercontent.com/6421576/132386156-cc402f35-1fd2-438f-aa6b-47627e712ea6.png)

Is this a false positive?
Thanks

**Comment by elibroftw** [comment]
Yes it's a false positive. I'm just going to end up rolling back pyinstaller later.
