### ISSUE TITLE
No devices detected

### ISSUE THREAD

**Issue by onegrasshopper** [elibroftw/music-caster#30]
win10, installed version, 4.90.101
firewall disabled

Music caster is not detecting any devices on the local network?
VLC detects the devices fine in the renderer setting so the devices are definitely discoverable. (so does chrome, etc)

kindly advise how I can help debug this. thank you

**Comment by elibroftw** [comment]
Which devices are not being detected?

**Comment by elibroftw** [comment]
Have you tried restarting the computer? The only reason I haven't updated the libraries responsible for the detection is because it was inconsistent in detecting devices. I'll look into his issue today by trying to update the libraries.

**Comment by onegrasshopper** [comment]
3 different google home's. None detected.
Yes, tried rebooting.
(just tested ChromeCast-Desktop-Audio-Streamer which worked too.)

Fyi, I have more thane one network interface if that matters to the discovery library binding to one ip or searching on all. It should not matter as I just tried on an older laptop which also has wifi and ethernet and Music Caster worked fine.

Thank you for looking into this.

**Comment by elibroftw** [comment]
Can you try the latest update?

**Comment by onegrasshopper** [comment]
It worked!!

**Comment by elibroftw** [comment]
Ayyy let's go.
