### ISSUE TITLE
Error launching Music Caster

### ISSUE THREAD

**Issue by koharski** [elibroftw/music-caster#35]
When launching an error shows "To run this application, you must install .NET Core."
Downloaded and installed but still getting error.

**Comment by elibroftw** [comment]
Is this portable? 

Install music Caster with the setup. I think you can also get away with deleting updater.exe.

**Comment by koharski** [comment]
Yes using the portable. Deleted updater.exe and it opened that time.
Do I need the .NET Core installed?
I had Music Caster running yesterday without it.
Thanks

**Comment by elibroftw** [comment]
Only if you want auto-updates. 
I used C# for the portable updater just because Python would result in a slow and sizable executable.

**Comment by koharski** [comment]
Nah I don;t care about the updater. Is it better to install using the setup.exe rather than the portable,

**Comment by koharski** [comment]
Its a nice program good job. Thanks for your work.

**Comment by elibroftw** [comment]
Yes it's better to install using the setup.exe. The portable has a slower startup because it needs to self extract every time the program is run.

**Comment by koharski** [comment]
Perfect. Thanks again!!
