### ISSUE TITLE
Music Caster suddenly cannot start anymore

### ISSUE THREAD

**Issue by segner** [elibroftw/music-caster#39]
Since maybe 2 hours, I cannot start the Windows app anymore. I receive this error message during startup:

> Failed to execute script 'music_caster' due to unhandled exception: 'charmap' codec can't decode byte 0x81 in position 74: character maps to <undefined>

> Traceback (most recent call last):
  File "music_caster.py", line 202, in <module>
  File "music_caster.py", line 132, in activate_from_lock_file
  File "music_caster.py", line 42, in is_already_running
  File "music_caster.py", line 33, in get_running_processes
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 74: character maps to <undefined>

I speculate you deployed a new version via auto update. But I also made some config changes in my audio settings, which could have led to this problem...

**Comment by segner** [comment]
By the way, I have the non-portable version installed (latest).

**Comment by segner** [comment]
After uninstall and re-install, the app started working again.

**Comment by elibroftw** [comment]
Issues was because of an encoding thing. Should be good now.

**Comment by segner** [comment]
The issue came back! There is a slightly different error message, now:

![image](https://user-images.githubusercontent.com/1880598/151660487-1242502e-4076-40cf-b23e-0409116ad090.png)


> Traceback (most recent call last):
  File "music_caster.py", line 202, in <module>
  File "music_caster.py", line 132, in activate_from_lock_file
  File "music_caster.py", line 42, in is_already_running
  File "music_caster.py", line 33, in get_running_processes
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 74: invalid start byte

I upgraded to version 5.1.13, but the issue persists...

**Comment by elibroftw** [comment]
I'll look into it. Leaving this here for me https://stackoverflow.com/questions/65591849/unicodedecodeerror-charmap-codec-cant-decode-byte-0x81-in-position-2483-cha

**Comment by elibroftw** [comment]
Fixed, although you may receive a different error message.

**Comment by segner** [comment]
I can confirm that the new version (v5.1.14) does not show the error during startup. I will report, if it starts acting up again. Thank you for your support!
