### ISSUE TITLE
higher compatibilty

### ISSUE THREAD

**Issue by resurrecta** [elibroftw/music-caster#4]
Greetings,
I stumbled upon this app to stream to my Google Nest speakers.
It is working, however I can't stream flac. Is a larger file compatibility planned?

**Comment by elibroftw** [comment]
It is planned, its just that I also have to add support for FLAC locally as well which is going to be a pain since I have to do all the donkey work myself. I have a whole month so I'm going to try to push the feature out by early June.

**Comment by resurrecta** [comment]
Ah thanks for the feedback. I'll make sure to follow this. This app is the next best thing since Google Nest can't play local files over the LAN otherwise. Keep it up.
One last question though (I'm a noob, so forgive me), but is there a way that Google Nest can use "previous and next" while using a playlist on this stream?

**Comment by elibroftw** [comment]
Nope, that's why there's a web GUI so if you don't want to go back to your
computer just go to settings, scan the qr code and control playback from
your mobile browser.

Elijah Lopez

**Comment by elibroftw** [comment]
Check out the new update
