### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll missing

### ISSUE THREAD

**Issue by Equax** [elibroftw/music-caster#40]
Hello,

trying with Portable and Install Version on Windows 7, the app will not start showing an error popup that api-ms-win-core-path-l1-1-0.dll is missing.

Are there any pre-requisits?

Thanks
Kevin

**Comment by elibroftw** [comment]
Which version is this?

**Comment by elibroftw** [comment]
@Equax

**Comment by Equax** [comment]
I tried both 5.1.18 and 5.1.19, and get the same error.

**Comment by elibroftw** [comment]
Windows 7 is not supported by the latest Python 3.10. You'll have to upgrade your os.

**Comment by elibroftw** [comment]
https://github.com/elibroftw/music-caster/releases/tag/v4.90.157

**Comment by elibroftw** [comment]
You'll have to manually disable auto-update from `settings.json`.

If you encounter any bugs, you'll have to install python3.8 32-bit and merge master into the 32-bit branch, resolve the merge conflicts, and then build it yourself https://github.com/elibroftw/music-caster/wiki/Developer-Guide. 

I'm closing this, but feel free to comment if you have any more questions.

**Comment by Equax** [comment]
Thanks this version does work, but I can't, for the life of me, find out how to cast the music. Is there no button to choose an output device?

**Comment by elibroftw** [comment]
You can right click the tray icon, and the select the device. Watch the demo if you are still confused.

**Comment by elibroftw** [comment]
Yeah I'm not going to be changing anything to fix that bug.
