### ISSUE TITLE
Keyboard shortcut for exiting program?

### ISSUE THREAD

**Issue by tomhammond** [elibroftw/music-caster#41]
Thanks for the excellent program, Elijah!  I started using Music Caster for the first time last evening.

I like the numerous keyboard shortcuts available in the program.  May you add a shortcut for fully closing the program (including the system tray icon)?  That way I can create macros that will start Music Caster, play some music, then close it all with keyboard shortcuts.

Thank you!

Tom Hammond
tominohio@gmail.com

**Comment by elibroftw** [comment]
There's an --exit option you can supply. But I'll add ctrl + shift + w none the less.

**Comment by tomhammond** [comment]
Thank you, Elijah!  That will be most helpful.  I need to find out what all
of the command line options are.  What a flexible program Music Caster is.
thanks!

**Comment by elibroftw** [comment]
One more thing. You can even make a request to 127.0.0.1:2001/exit to trigger the exit, but you have to iterate both 2001 and 2002 in case the app could not bind to the 2001 prot.
