### ISSUE TITLE
May you add a command line option to choose the device to stream to?

### ISSUE THREAD

**Issue by tomhammond** [elibroftw/music-caster#42]
Hi Elijah,

I noticed that in the json file, the "previous_device" field contains the address to the current smart device that music will be cast to.  This way, the next time one starts Music Caster, it will default to this device.

May you make a command line option to specify a device address at startup?  I can learn the various device addresses by activating them via the system icon, then viewing the json file.

As an aside, I am able to start and control Music Caster with my voice via Google Home.  I can choose various playlists via voice, too.  If you are interested in the idea, I can email the instructions I wrote to do this.

Thanks!
Tom

**Comment by elibroftw** [comment]
Sure and to get a list of devices, check out https://github.com/elibroftw/music-caster/wiki/REST-API. I'm not going to be adding big features for some time so you can add the instructions in this issue so I can take a look at it in the future.

**Comment by elibroftw** [comment]
You can now use `--device=local|UUID`

**Comment by tomhammond** [comment]
Thank you, Elijah!  I will try the new --device parameter tomorrow evening.  That is wonderful!

**Comment by tomhammond** [comment]
OK, thanks for the API link.

 

The voice control solution is messy; I use a Logitech Harmony hub as the conduit to Google Home; the hub sends virtual keystrokes via Bluetooth to the computer running Music Caster.  But it works well.  There are better ways to do voice control, but this works with in my skill level.  😊

 

I’ll send the instructions over the weekend.

 

Thanks for all of your help.  Music Caster is wonderful!

Tom

**Comment by elibroftw** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Verdana;
	panose-1:2 11 6 4 3 5 4 4 2 4;}
@font-face
	{font-family:"Segoe UI Emoji";
	panose-1:2 11 5 2 4 2 4 2 2 3;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.DefaultFontHxMailStyle
	{mso-style-name:"Default Font HxMail Style";
	font-family:"Verdana",sans-serif;
	color:windowtext;
	font-weight:normal;
	font-style:normal;
	text-decoration:none none;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
