### ISSUE TITLE
[Bug] Multiple Instances if many Runs

### ISSUE THREAD

**Issue by tomhammond** [elibroftw/music-caster#43]
Hi Elijah,

Would you consider adding a feature to Music Caster so that it only allows one instance at startup?  That is, to prevent multiple copies of the program from running at the same time.  

The situation is this: When I tell Google Home to start playing music, there are multiple speakers in my house listening for commands.  Sometimes those multiple speakers trigger the command simultaneously to Music Caster at the same time.  

When this happens, there are multiple, identical streams being sent to the smart speakers, causing playback to be choppy on some speakers, even causing them to temporarily break connection to wifi.  

If Music Caster can avoid starting if it detects itself already running, that would help.  The trick is, Google Home fires the commands to start multiple instances of MC in rapid succession, so the first instance may not be fully loaded before the second instance attempts to start.  Perhaps add a feature so that MC creates a registry key as the first very thing it does at startup to indicate that it is starting, then other instances can check for they key when they attempt to start.

Thanks so much for your help.  Music Caster is truly wonderful; I use it every day for my house music!

Take care,
Tom Hammond

**Comment by elibroftw** [comment]
I did have pid files to detect multiple instances and had extra guards against it but I'll take a look again.

**Comment by tomhammond** [comment]
Thanks for looking into this.  I did a lot of troubleshooting; I know the
problem is not with my router or wifi.  If I close the office door so that
only one speaker hears my command, Music Caster mostly works perfectly fine
when I trigger it by voice command.

Maybe your pid files and other guards only work *after* the first instance
has fully loaded?  In my case, I think the first instance has partially
loaded when the second instance tries to start up, creating a conflict.
That's just a guess. :)

Thanks!
Topm

**Comment by elibroftw** [comment]
What happens is that the other instances start so fast that they read the same pid file that the first instance read. My guards are placed after the port binding to make a request to the server. What I think I'll do is move the guards down until the command line paths would be played.

**Comment by tomhammond** [comment]
I noticed that when choppy music happens during casting (I assume it's from
multiple instances of Music Caster trying to stream at the same time),
closing Music Caster does not stop the streaming.  There is still choppy
playback on the speakers, at least until the current MP3 file finishes.
Even rebooting the computer does not stop this playback.  The smart
speakers are in an unable state for a while, unable to recover to normal
mode.  Some even lose connection to wifi, which is strange.  The problem
isn't with the router; I replaced it with a stronger one.

My guess is that the speakers are receiving multiple, identical streams
from multiple instances of Music Caster, which confuses the speakers and
causes the choppy playback.  Also note that I am casting to a speaker group.

Casting and voice control work fine when I am giving the commands to one
speaker (and I ensure they others are not listening).  That's why I think
it is a problem with multiple instances of streaming.  It's my best guess.

Thanks,
Tom

**Comment by elibroftw** [comment]
It's choppy because Music Caster has a server which isn't production. It is my fault partly, I just haven't bothered switching it to something for production because there wasn't a use case to need multiple connections. Are you exiting the program using the keyboard binding or the tray? Both should stop playback for their respective chromecasts.

**Comment by tomhammond** [comment]
Sounds good.  I am happy to help with troubleshooting that you want me to
try on this end.  :)

**Comment by tomhammond** [comment]
If I remember correctly, I think I am using the command line argument
--exit to exit the program.  I have also tried exiting via the tray.  Both
seem unable to halt playback while the choppy audio problem is happening.

As an aside, is there a keyboard shortcut for advancing to the next song in
a queue?

Thanks,
Tom

**Comment by elibroftw** [comment]
The next track shortcut is the keyboard defined shortcut/button for it. There should be a symbol on your keyboard for it. I'll add the shortcut if your keyboard doesn't support it.

**Comment by elibroftw** [comment]
Also, I think your voice commands will screw up the player unless you are using a cast group.

**Comment by tomhammond** [comment]
My keyboard doesn't have a next track button on it; could you add a
shortcut for a regular key for skipping to next track?  Thanks.

**Comment by tomhammond** [comment]
I am using a cast group.  Did you make changes to the multi-instance guard
code?  Is there an updated version of MC that you want me to try?

Thanks,
Tom

**Comment by elibroftw** [comment]
Yes try the latest one. I tested quick launches and only one instance was created

**Comment by tomhammond** [comment]
OK, I will try that version tonight.  Thank you!

Tom

**Comment by elibroftw** [comment]
There's links to donate in the readme. You're welcome and thanks for the feedback as it forces me to improve the program.

**Comment by tomhammond** [comment]
OK, donation sent!  😊
