### ISSUE TITLE
MP3 tag problem

### ISSUE THREAD

**Issue by tomhammond** [elibroftw/music-caster#46]
Music Caster has trouble reading MP3 tags from most of my MP3 files.  It reads the cover art on all files, but cannot read the album/artist/title on many of them.  Please see the attached screenshot.  The 03, 10, 16, etc. represent filenames.

All of my MP3s show the tag information properly in other music programs such as Win 11 Media Player, WinAmp, and VLC.

When I open the “bad” and “good” MP3 files in the “MP3tag” program, they all have ID3v2.3 and ID3v1 tags set (both MP3s that show properly in Music Caster and MP3s that do not show properly).  So I don’t know why some MP3s are not showing their MP3 tags in Music Caster while other MP3 files show tag information fine.

Attached are examples of a “good” MP3 and a “bad” MP3, as shown in the screenshot.  Can you help?

Thanks,
Tom
![screenshot](https://user-images.githubusercontent.com/19535367/157142027-2732c790-557b-4a1c-878b-41d285af11b3.jpg)
[06 (bad).zip](https://github.com/elibroftw/music-caster/files/8201739/06.bad.zip)
[01 (good).zip](https://github.com/elibroftw/music-caster/files/8201749/01.good.zip)

**Comment by elibroftw** [comment]
Oh, it might just be because the extension is capitalized. I had it in my todo to not depend on file extensions, so I will fix that bug now.

**Comment by tomhammond** [comment]
I hadn’t thought of that.  Good idea.  I will check other “bad” MP3 files and see if that is the common problem.  Thanks so much!

**Comment by elibroftw** [comment]
Should be fixed now.
