### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by Benlge** [elibroftw/music-caster#5]
![Annotation 2020-06-25 204854](https://user-images.githubusercontent.com/64033346/85781132-a9489280-b725-11ea-8259-228862c47be1.png)

Musique Caster v4.49.4 for Windows 10 x64

>Music.Caster.x64.Setup.exe

"Fatal error detected.
Failed to execute script music_caster"
always at program start.

-On Windows 10x64 2004.
-Using: .exe and Portable.

**Comment by elibroftw** [comment]
I'm on Windows 10 v2004 right now and it works fine for me. You will have to install Python 3.6, install the dependencies and then run `music_caster.py` yourself. Clone the repository.

**Comment by Benlge** [comment]
Hi,

Thank you for your answer. 
Excuse me but I'm new to GitHub, and still don't understand how to do it. How and where to download Python 3.6? How install the dependencies and then run music_caster.py myself, and Clone the repository? Can you guide me and explain myself? Because I am lost. I know absolutely nothing sorry.

Thank you in advance.

Ben

**Comment by elibroftw** [comment]
I just made https://github.com/elibroftw/music-caster/wiki/Development-Guide. Tell me if you have any troubles or need any clarification.

**Comment by elibroftw** [comment]
Also if you don't get any errors running it in Python, first use `python build.py` to test if the issue is still present and then `python build.py --debug` to see if the error is a GUI error.

**Comment by elibroftw** [comment]
I updated the app a lot, could you tell me if this is still an issue @Benlge
