### ISSUE TITLE
Winget version seems to install crypto miner

### ISSUE THREAD

**Issue by Build-0-Matic** [elibroftw/music-caster#54]
Just to let you know that the version that you download using winget seems to download a crypto miner. It gets flagged right away by the antivirus software.

**Comment by elibroftw** [comment]
Windows Anti-Virus reports it as a crypto miner?

**Comment by elibroftw** [comment]
Is the setup flagged or the actual executable?

**Comment by Build-0-Matic** [comment]
Avast flags it as unwanted and blocks the connection. So I told it to whitelist it and installed anyway. Then I went to run it and Avast once more blocked the program. So I went to the install folder and found about 50 files including some that say they are related to crypto. There is no updater present like on the portable version. It has a ton of timezone data and a whole bunch of files and folders that I don't recognize from the portable version.

**Comment by elibroftw** [comment]
Okay I will file a report with Avast

**Comment by Build-0-Matic** [comment]
I'd try and do a winget update on my machine first as I'm really not sure that what it installs is what you put online. I feel somebody is taking advantage of the situation as the only thing in the program that looks remotely like the portable one is the icon and the name. As I said, it's got no updater and a whole lot of other stuff not found in the portable version.

**Comment by elibroftw** [comment]
You'll have to whitelist the install folder in avast since avast doesn't want to whitelist music Caster.
