### ISSUE TITLE
Aiff (.aiff) file format support

### ISSUE THREAD

**Issue by subtilt** [elibroftw/music-caster#55]
Any possibility of getting playback support for the .aiff file format in the near future?

Now, I might've missed something but I can't get it to cast .aiff files. It just turns silent whenever I try and cast so I assume that it means no .aiff support at this moment in time. It'd be highly appreciated if support for this file format is added in the future.

**Comment by elibroftw** [comment]
https://support.google.com/chromecast/answer/6279377?hl=en

In the future sure, however I'd need to learn how to convert aiff to wav on the fly.

**Comment by subtilt** [comment]
Ah ok! Thanks for letting me know. Brilliant work by the way.

**Comment by elibroftw** [comment]
Completed?
