### ISSUE TITLE
Can't access the settings tray

### ISSUE THREAD

**Issue by Zefros86** [elibroftw/music-caster#6]
After installing I can't seem to access the settings tray when right clicking the icon on the taskbar. Nothing comes up when right clicking on it. It installed and runs fine, seems odd.
exe and portable version
Running on Windows 10 LTSB 2016 x64 v1607

**Comment by elibroftw** [comment]
What version of music caster? Have you tried Reinstalling or deleting the settings file?

**Comment by elibroftw** [comment]
Also how about left clicking the icon. Does left clicking work?

**Comment by elibroftw** [comment]
Any update on this @Zefros86 ?
