### ISSUE TITLE
UI: pop-up windows have no text

### ISSUE THREAD

**Issue by glaubway** [elibroftw/music-caster#61]
Hi, 
when I have moved cursor to a icon (checked with icons in the queue tab) and pop-up window was being showed I had observed no text in this window.

Version - 5.13.17 (Portable)

![image](https://user-images.githubusercontent.com/16296930/232335529-89531e5b-40de-48b9-b686-30c0e7e4fab4.png)

**Comment by elibroftw** [comment]
Did you check the experimental ui to get this or is this the default ui?

**Comment by glaubway** [comment]
Oh, you're right, I have checked "Experimental features".
If this is expected behaviour, I can close the issue.

**Comment by elibroftw** [comment]
It's not expected behavior, but it's experimental for a reason 😂. Thanks for bringing it up though, the reason this ui is experimental is because it's slow not because of bugs.

**Comment by VOOM108** [comment]
The experimental UI is great (matches Win 11 nicely), and for me seems not slow at all. 

About the missing tooltips: I suppose, the text is there, but the color is the same as the background.

**Comment by elibroftw** [comment]
@VOOM108 thanks for the comment, you gave me motivation to do some research and fix this issue
