### ISSUE TITLE
Music Caster update detected as Trojan

### ISSUE THREAD

**Issue by jwatte** [elibroftw/music-caster#65]
Music Caster auto-updated, and Windows detected it as a Trojan.
I don't know if it's a false positive, or whether you got supply chain attacked, but the README should probably say something about this ...

**Comment by elibroftw** [comment]
Yeah it's a false positive. I updated pyinstaller and it caused all this mess. I did revert the pyinstaller version so try the latest update?

I probably won't update pyinstaller again so now worries.
