### ISSUE TITLE
online .m3u8 or .mp3 feed possible?

### ISSUE THREAD

**Issue by appel** [elibroftw/music-caster#7]
Would it possible to link to an online .m3u8 or .mp3? I would love to be able to cast freecodecamp radio, the link to their audio stream is https://coderadio-admin.freecodecamp.org/radio/8010/radio.mp3.

Thanks!

**Comment by elibroftw** [comment]
yea I'll modify the play url function. Right now I am fixing the auto update

**Comment by appel** [comment]
Thanks!

**Comment by elibroftw** [comment]
Okay so for some reason it'll take about 10 - 15 seconds for the chromecast to start playing. I'll look into this later as I'm tired right now but the latest version lets you play from a .mp3 url.

**Comment by appel** [comment]
Thanks for working on this, much appreciated! I downloaded and installed the latest version, and added `https://coderadio-admin.freecodecamp.org/radio/8010/radio.mp3` in the Play URL box, but I can't get it to play for some reason. The stream won't show up in the queue either. I also tried a [Youtube link](https://www.youtube.com/watch?v=wAR_bdvqYeE) just in case, but that won't play either, not locally and not on my devices.

**Comment by elibroftw** [comment]
Play URL is only supported when you are connected to a Chromecast. I'm on the latest version too and it takes 15 - 20 seconds for it to start playing the radio URL. Youtube URLs take 5 seconds max. e.g. https://youtu.be/x0RXU3n1GM0

**Comment by appel** [comment]
You're right, that worked, awesome! Took about 10 seconds here to start playing. Unrelated issue, but I noticed that my cast groups (for multiroom audio) are not showing up under Devices. Should I create a separate issue for that? Thanks!

**Comment by elibroftw** [comment]
Yeah sure
