### ISSUE TITLE
Hard coded UI strings on Timer tab

### ISSUE THREAD

**Issue by fz0000** [elibroftw/music-caster#72]
I found that some UI strings are not translated.
e.g.

https://github.com/elibroftw/music-caster/blob/0b9bc54d3d381d11b6c3032bd959892f7924051e/src/music_caster.py#L3285
![image](https://github.com/elibroftw/music-caster/assets/5061311/3dc8c0ff-abd9-43ea-8c5a-e6fd00681d55)

and

https://github.com/elibroftw/music-caster/blob/0b9bc54d3d381d11b6c3032bd959892f7924051e/src/music_caster.py#L2785
https://github.com/elibroftw/music-caster/blob/0b9bc54d3d381d11b6c3032bd959892f7924051e/src/music_caster.py#L3275
![image](https://github.com/elibroftw/music-caster/assets/5061311/cb50cb29-ecf1-46c6-b97f-5702b9adfea2)

---
By the way, it seems that the following string is not in the translation file. But I think it's acceptable:
https://github.com/elibroftw/music-caster/blob/0b9bc54d3d381d11b6c3032bd959892f7924051e/src/gui/views.py#L361
![image](https://github.com/elibroftw/music-caster/assets/5061311/9638118f-8425-4a89-b30f-891cd360d663)

**Comment by elibroftw** [comment]
As for the credits text, yeah that was done intentionally even though "by" isn't really a word in other languages.
