### ISSUE TITLE
Recent releases seem to have broken almost all functionality on Windows 11

### ISSUE THREAD

**Issue by mikecarnohan** [elibroftw/music-caster#75]
Not sure what changed, but on my windows 11 laptop, that can cast from youtube, and other apps, I'm no longer getting almost anything funcitoning correctly in the app. The local device option doesn't play audio through the sound card and the cast options look the same, but are not sending cast information successfully. 

Anyone else experiencing these issues? I'm happy to shoot a more detail setup list to you to try and start a debug session.

**Comment by elibroftw** [comment]
It seems there is another error as well. Let me fix that

**Comment by mikecarnohan** [comment]
Let me know when you have a build ready to test. I'll give you a full report (including setups tested and findings).

**Comment by elibroftw** [comment]
Can you try the latest? I pushed an update yesterday which will fallback on the local device. I don't know what's wrong with my Chromecast. I've already filed issues with the underlying library so we'll see what's going on.

**Comment by elibroftw** [comment]
@mikecarnohan can you also provide the ipconfig of your device? I recently fixed a bug with casting to a chromecast
