### ISSUE TITLE
Support for Audio Cast groups under 'Devices'

### ISSUE THREAD

**Issue by appel** [elibroftw/music-caster#8]
I have 3 Audio Cast groups (for multi-room audio) in my home through which I play music, but these are currently not showing up under Devices.

These three groups are viewable via the Google Home app:

![image](https://user-images.githubusercontent.com/61596/86790061-fbe35200-c035-11ea-8da1-1625375d6baa.png)

But not via the Select Device menu:

![image](https://user-images.githubusercontent.com/61596/86790431-6e543200-c036-11ea-8c09-44f3e2b727f7.png)

**Comment by elibroftw** [comment]
Okay, try the latest installation. I don't have any groups myself so I can't test it out.

**Comment by appel** [comment]
Hey @elibroftw, I just installed the most recent version (4.54.5). Unfortunately, groups still aren't showing up. Tried 'Refresh Devices' but no dice.

**Comment by elibroftw** [comment]
Let me make a group with my office speaker and my Chromecast and then I'll see what's going on

**Comment by elibroftw** [comment]
Did a lot of research today and thought of a solution to my Chromecast detection issues before (4+ months ago). Check out the latest update.

**Comment by appel** [comment]
It works, this is great! Thanks so much!

![image](https://user-images.githubusercontent.com/61596/86978446-f593c980-c14c-11ea-897a-da05c8072066.png)

Of course this just triggers more ideas... :) Is there a way to sort the list so that all groups are on top? I almost never cast to a single device, always to a group first.

**Comment by elibroftw** [comment]
done
